# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
 - LUA_LUACHECK
 - RUST_CLIPPY
 - JAVASCRIPT_ES
 - CSS_STYLELINT
 - MARKDOWN_MARKDOWNLINT
 - YAML_YAMLLINT
 - JSON_ESLINT_PLUGIN_JSONC
 - HTML_DJLINT
 - ACTION_ACTIONLINT
 - DOCKERFILE_HADOLINT
 - SPELL_CSPELL
 - COPYPASTE_JSCPD
 - REPOSITORY_TRIVY
# DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
