---
name: Welcome first time contributors 

on:
  pull_request_target:
    types:
      - opened
 
jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/first-interaction@2c1a690e6b60f93eb33eb4a15b9a12afbb4f2f21 # v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congrats on making your first Pull Request and thanks for taking the time to improve Websurfx! ❤️!
            Say hello by joining the conversation in our [Discord](https://discord.gg/SWnda7Mw5u)
