---
# .github/workflows/docker-build-on-tag.yml
name: Docker Image CI on Tag

on:
  push:
    branches:
      - rolling
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v1.2.3, etc.

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      packages: write # Required if pushing to GitHub Packages
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test variables
        run: |
          [ -z ${{ secrets.DOCKER_USERNAME }} ] && echo "no username" && exit 1
          [ -z ${{ secrets.DOCKER_PASSWORD }} ] && echo "no PASSWORD" && exit 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/websurfx # Your Docker Hub repo name (e.g., myuser/myrepo)
          tags: |
            type=semver,pattern={{version}} # Uses the Git tag (e.g., v1.0.0 -> 1.0.0)
            type=raw,value=latest,enable=${{ endsWith(github.ref, 'latest') }} # Pushes 'latest' tag if the Git tag is 'latest'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile's context (usually the root of the repo)
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Cache layers using GitHub Actions cache
          cache-to: type=gha,mode=max # Store cache layers
